# Generated by Django 3.1.4 on 2021-01-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_sweets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
