# Generated by Django 3.1.4 on 2021-01-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sweets',
        ),
    ]
